.TH FINDDUPES 1
.SH NAME
finddupes \- finds duplicate files in a given set of directories

.SH SYNOPSIS
.B finddupes
[
.I options
]
.I PATH
\|.\|.\|.

.SH "DESCRIPTION"
Searches the given paths for duplicate files. Such files are found by
comparing file sizes and MD5 signatures.

.SH OPTIONS
.TP
.B -r --recursive
for every directory given follow subdirectories encountered within
.TP
.B -s --symlinks
follow symlinked directories and compare files pointed to by their links;
normally symlinked directories and files are skipped
.TP
.B -H --hardlinks
normally, when two or more files point to the same disk area they are
treated as non-duplicates; this option will change this behavior
.TP
.B -n --noempty
exclude zero-length files from consideration
.TP
.B -f --omitfirst
omit the first file in each set of matches
.TP
.B -u --unique
list only files that don't have duplicates
.TP
.B -q --quiet
hide progress indicator
.TP
.B -p --separator=sep
separate files with sep string instead of '\\n'
.TP
.B -P --setseparator=sep
separate sets with sep string instead of '\\n\\n'
.TP
.B -v --version
display finddupes version and exit
.TP
.B -h --help
display this help and exit

.SH NOTES
Unless
.B --separator
or
.B --setseparator
are specified, duplicate files are listed
together in groups, each file displayed on a separate line. The
groups are then separated from each other by blank lines.

.SH EXAMPLES
Remove all duplicate files in a directory tree, ask for individual
confirmation on each file.

NOTE that this works only if filenames do not contain '\\n', '\\x00' or '\\x01'.

.fam C
finddupes -r --separator '\\x01' --setseparator '\\x00' someDir |
    xargs -0 -n1 -I{} sh -c '
        s=$(echo {} | tr "\\001" "\\n"); echo -e "$s"; \\
        echo -n {} | tr "\\001" "\\000" | xargs -0pr -n1 rm'
.fam T

Preserve files in a good tree, remove duplicates elsewhere.
Say you want to look for dupes in two trees,
.BR goodTree
and
.BR badTree ,
and, in
case of duplicates, you want to preserve a copy in
.BR goodTree
and remove any other dupes. Note that, in each set, files inside the first tree
appear before files inside the second one. The order in which duplicate sets
are printed is not determined though.

NOTE that this removes files without confirmation.

.fam C
finddupes -r --omitfirst -p '\\x00' -P '\\x00' goodTree badTree |
    xargs -0 rm
.fam T

Find out how much disk space is occupied by duplicate files:

.fam C
finddupes -rf -p '\\x01' -P '\\x00' someDir/ |
    xargs -0 -n1 -I{} sh -c '
        echo -n {} | tr "\\001" "\\000" | xargs -0r du -csh'
.fam T

Or, more compact, with a grand total but without detailing the usage of each
set:

.fam C
finddupes -rf -p '\\x00' -P '\\x00' someDir/ | xargs -0 du -ch
.fam T

List files without duplicates whose contents are present in
.BR treeA
but not in
.BR treeB :

.fam C
finddupes --recursive --unique treeA treeB | grep '^treeA/'
.fam T

.SH BUGS
If you find a bug, please report it via <http://github.com/jesrui/finddupes/issues>.

.SH ACKNOWLEDGEMENTS
.B finddupes
draws heavily from
.B fdupes
<https://github.com/adrianlopezroche/fdupes>.
